# Generated by Django 2.2.1 on 2019-05-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataneed',
            name='themes',
            field=models.ManyToManyField(blank=True, to='data_manager.Theme'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='attribute_fields',
            field=models.ManyToManyField(blank=True, to='data_manager.AttributeInfo'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='lookup_table',
            field=models.ManyToManyField(blank=True, to='data_manager.LookupInfo'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='sublayers',
            field=models.ManyToManyField(blank=True, related_name='_layer_sublayers_+', to='data_manager.Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='themes',
            field=models.ManyToManyField(blank=True, to='data_manager.Theme'),
        ),
        migrations.AlterField(
            model_name='toc',
            name='themes',
            field=models.ManyToManyField(blank=True, to='data_manager.TOCTheme'),
        ),
        migrations.AlterField(
            model_name='tocsubtheme',
            name='layers',
            field=models.ManyToManyField(blank=True, to='data_manager.Layer'),
        ),
        migrations.AlterField(
            model_name='toctheme',
            name='layers',
            field=models.ManyToManyField(blank=True, to='data_manager.Layer'),
        ),
        migrations.AlterField(
            model_name='toctheme',
            name='subthemes',
            field=models.ManyToManyField(blank=True, to='data_manager.TOCSubTheme'),
        ),
    ]
