# Generated by Django 2.2.1 on 2019-06-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_auto_20190529_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='order',
            field=models.IntegerField(default=999),
        ),
    ]
