# Generated by Django 2.2.1 on 2019-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0004_auto_20190606_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='toctheme',
            name='order',
            field=models.IntegerField(default=999),
        ),
    ]
