# Generated by Django 2.2.1 on 2019-06-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0006_auto_20190606_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='auto_ident_open',
            field=models.BooleanField(default=False, verbose_name='Auto-Open Identify Window'),
        ),
    ]
