# Generated by Django 2.2.1 on 2019-05-29 09:35

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField(blank=True, null=True)),
                ('hex_id', models.IntegerField(blank=True, default=None, null=True)),
                ('auspatid', models.IntegerField(blank=True, default=None, null=True)),
                ('ecoregion', models.TextField(blank=True, default=None, null=True)),
                ('coa_name', models.TextField(blank=True, default=None, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('fish', models.TextField(blank=True, null=True)),
                ('obs_spec', models.TextField(blank=True, null=True)),
                ('mod_spec', models.TextField(blank=True, null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Grid Cell Geometry')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('habitat', models.BooleanField()),
                ('fish', models.BooleanField()),
                ('obs_spec', models.BooleanField()),
                ('mod_spec', models.BooleanField()),
                ('description', models.TextField(blank=True, null=True)),
                ('satisfied', models.BooleanField(default=True, help_text='Am I satisfied?')),
                ('active', models.BooleanField(default=True)),
                ('grid_cells', models.TextField(blank=True, null=True, verbose_name='Grid Cell IDs')),
                ('geometry_final_area', models.FloatField(blank=True, null=True, verbose_name='Total Area')),
                ('geometry_dissolved', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857, verbose_name='Filter result dissolved')),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='scenarios_scenario_related', to='contenttypes.ContentType')),
                ('sharing_groups', models.ManyToManyField(blank=True, editable=False, null=True, related_name='scenarios_scenario_related', to='auth.Group', verbose_name='Share with the following groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios_scenario_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
