# Generated by Django 2.2.1 on 2019-06-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mp_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marineplannersettings',
            name='table_of_contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_manager.TOC'),
        ),
    ]
