SPECIES_LOOKUP = {
    '216': u'Olive-sided Flycatcher',
    '217': u'Willow Flycatcher',
    '214': u'Short-eared Owl',
    '215': u'Common Nighthawk',
    '212': u'Southern Torrent Salamander',
    '213': u'Grasshopper Sparrow',
    '210': u'Northern Red-legged Frog',
    '211': u'Cascade Torrent Salamander',
    '450': u'California Myotis',
    '451': u'Fringed Myotis',
    '452': u'Western Gray Squirrel',
    '453': u'Northern Pacific Pond Turtle',
    '454': u'Western Painted Turtle',
    '455': u'Western Rattlesnake',
    '456': u'Chipping Sparrow',
    '219': u'Acorn Woodpecker',
    '565': u'Bull Trout',
    '584': u'Coho Salmon',
    '595': u'Steelhead, Summer Run',
    '496': u'OCS Habitat - Flowing Water and Riparian',
    '230': u'Northern Pacific Pond Turtle',
    '231': u'Western Painted Turtle',
    '232': u'Chipping Sparrow',
    '559': u'OCS Habitat -  Wetland, high conservation significance',
    '597': u'Steelhead, Winter Run',
    '577': u'Chum Salmon',
    '429': u'Clouded Salamander',
    '209': u'Oregon Slender Salamander',
    '520': u'OCS Habitat - Oak Woodlands',
    '208': u'Clouded Salamander',
    '570': u'Chinook Salmon, Fall Run',
    '502': u'OCS Habitat - Grasslands',
    '586': u'Oregon Chub',
    '449': u'Hoary Bat',
    '448': u'Silver-haired Bat',
    '580': u'Coastal Cutthroat Trout',
    '443': u'Western Purple Martin',
    '442': u'Oregon Vesper Sparrow',
    '441': u'Acorn Woodpecker',
    '440': u'Yellow-breasted Chat',
    '447': u"Townsend's Big-eared Bat",
    '446': u'Western Meadowlark',
    '445': u'Northern Spotted Owl',
    '444': u'Western Bluebird',
    '218': u'Yellow-breasted Chat',
    '229': u'Columbian White-tailed Deer',
    '228': u'Fringed Myotis',
    '227': u'California Myotis',
    '226': u'Silver-haired Bat',
    '225': u"Townsend's Big-eared Bat",
    '224': u'Western Meadowlark',
    '223': u'Northern Spotted Owl',
    '222': u'Western Bluebird',
    '221': u'Western Purple Martin',
    '220': u'Oregon Vesper Sparrow',
    '512': u'OCS Habitat - Natural Lakes',
    '576': u'Chinook Salmon, Spring/Summer Run',
    '532': u'OCS Habitat - Wetland',
    '438': u'Olive-sided Flycatcher',
    '439': u'Willow Flycatcher',
    '436': u'Short-eared Owl',
    '437': u'Common Nighthawk',
    '434': u'Southern Torrent Salamander',
    '435': u'Grasshopper Sparrow',
    '432': u'Cascade Torrent Salamander',
    '433': u'Columbia Torrent Salamander',
    '430': u'Oregon Slender Salamander',
    '431': u'Foothill Yellow-legged Frog'
}
