SPECIES_LOOKUP = {
"1":u"Cascade Torrent Salamander",
"2":u"Cascade Torrent Salamander",
"3":u"Cascades Frog",
"4":u"Cascades Frog",
"5":u"Clouded Salamander",
"6":u"Clouded Salamander",
"7":u"Coastal Tailed Frog",
"8":u"Coastal Tailed Frog",
"9":u"Columbia Spotted Frog",
"10":u"Columbia Spotted Frog",
"11":u"Columbia Torrent Salamander",
"12":u"Columbia Torrent Salamander",
"13":u"Cope's Giant Salamander",
"14":u"Cope's Giant Salamander",
"15":u"Del Norte Salamander",
"16":u"Del Norte Salamander",
"17":u"Foothill Yellow-legged Frog",
"19":u"Larch Mountain Salamander",
"20":u"Larch Mountain Salamander",
"18":u"Foothill Yellow-legged Frog",
"21":u"Northern Red-legged Frog",
"22":u"Northern Red-legged Frog",
"23":u"Oregon Slender Salamander",
"24":u"Oregon Slender Salamander",
"25":u"Oregon Spotted Frog",
"26":u"Oregon Spotted Frog",
"27":u"Rocky Mountain Tailed Frog",
"28":u"Rocky Mountain Tailed Frog",
"29":u"Siskiyou Mountain Salamander",
"30":u"Siskiyou Mountain Salamander",
"31":u"Southern Torrent Salamander",
"32":u"Southern Torrent Salamander",
"33":u"Western Toad",
"34":u"Western Toad",
"35":u"Acorn Woodpecker",
"36":u"Acorn Woodpecker",
"37":u"Peregrine Falcon (American)",
"38":u"Peregrine Falcon (American)",
"39":u"American Three-toed Woodpecker",
"40":u"American Three-toed Woodpecker",
"41":u"American White Pelican",
"42":u"American White Pelican",
"43":u"Black-backed Woodpecker",
"44":u"Black-backed Woodpecker",
"45":u"Black-necked Stilt",
"46":u"Black-necked Stilt",
"47":u"Black Brant",
"48":u"Black Brant",
"49":u"Black Oystercatcher",
"50":u"Black Oystercatcher",
"51":u"Black Swift",
"52":u"Black Swift",
"53":u"Bobolink",
"54":u"Bobolink",
"55":u"Brewer's Sparrow",
"56":u"Brewer's Sparrow",
"57":u"Brown Pelican (California)",
"58":u"Brown Pelican (California)",
"59":u"Caspian Tern",
"60":u"Caspian Tern",
"61":u"Chipping Sparrow",
"62":u"Chipping Sparrow",
"63":u"Columbian Sharp-Tailed Grouse",
"64":u"Columbian Sharp-Tailed Grouse",
"65":u"Common Nighthawk",
"66":u"Common Nighthawk",
"67":u"Dusky Canada Goose",
"68":u"Dusky Canada Goose",
"69":u"Ferruginous Hawk",
"70":u"Ferruginous Hawk",
"71":u"Flammulated Owl",
"72":u"Flammulated Owl",
"73":u"Fork-tailed Storm-Petrel",
"74":u"Fork-tailed Storm-Petrel",
"75":u"Franklin's Gull",
"76":u"Franklin's Gull",
"77":u"Grasshopper Sparrow",
"78":u"Grasshopper Sparrow",
"79":u"Great Gray Owl",
"80":u"Great Gray Owl",
"81":u"Greater Sage-Grouse",
"82":u"Greater Sage-Grouse",
"83":u"Greater Sandhill Crane",
"84":u"Greater Sandhill Crane",
"85":u"Harlequin Duck",
"86":u"Harlequin Duck",
"87":u"Juniper Titmouse",
"88":u"Juniper Titmouse",
"89":u"Leach's Storm-Petrel",
"90":u"Leach's Storm-Petrel",
"91":u"Lewis's Woodpecker",
"92":u"Lewis's Woodpecker",
"93":u"Loggerhead Shrike",
"94":u"Loggerhead Shrike",
"95":u"Long-billed Curlew",
"96":u"Long-billed Curlew",
"97":u"Marbled Murrelet",
"98":u"Marbled Murrelet",
"99":u"Mountain Quail",
"100":u"Mountain Quail",
"101":u"Northern Goshawk",
"102":u"Northern Goshawk",
"103":u"Northern Spotted Owl",
"104":u"Northern Spotted Owl",
"105":u"Olive-sided Flycatcher",
"106":u"Olive-sided Flycatcher",
"107":u"Oregon Vesper Sparrow",
"108":u"Oregon Vesper Sparrow",
"109":u"Pileated Woodpecker",
"110":u"Pileated Woodpecker",
"111":u"Red-necked Grebe",
"112":u"Red-necked Grebe",
"113":u"Rock Sandpiper",
"114":u"Rock Sandpiper",
"115":u"Short-Eared Owl",
"116":u"Short-Eared Owl",
"117":u"White-breasted Nuthatch (Slender-billed)",
"118":u"White-breasted Nuthatch (Slender-billed)",
"119":u"Snowy Egret",
"120":u"Snowy Egret",
"121":u"Streaked Horned Lark",
"122":u"Streaked Horned Lark",
"123":u"Swainson's Hawk",
"124":u"Swainson's Hawk",
"125":u"Tufted Puffin",
"126":u"Tufted Puffin",
"127":u"Upland Sandpiper",
"128":u"Upland Sandpiper",
"129":u"Western Bluebird",
"130":u"Western Bluebird",
"131":u"Burrowing Owl (Western)",
"132":u"Burrowing Owl (Western)",
"133":u"Western Meadowlark",
"134":u"Western Meadowlark",
"135":u"Purple Martin",
"136":u"Purple Martin",
"137":u"Western Snowy Plover",
"138":u"Western Snowy Plover",
"139":u"White-headed Woodpecker",
"140":u"White-headed Woodpecker",
"141":u"Willow Flycatcher",
"142":u"Willow Flycatcher",
"143":u"Yellow-Breasted Chat",
"144":u"Yellow-Breasted Chat",
"145":u"Yellow Rail",
"146":u"Yellow Rail",
"147":u"American Marten",
"148":u"American Marten",
"149":u"California Myotis",
"150":u"California Myotis",
"151":u"Columbian White-tailed Deer",
"152":u"Columbian White-tailed Deer",
"153":u"Fisher",
"154":u"Fisher",
"155":u"Fringed Myotis",
"156":u"Fringed Myotis",
"157":u"Hoary Bat",
"158":u"Hoary Bat",
"159":u"Kit Fox",
"160":u"Kit Fox",
"161":u"Long-legged Myotis",
"162":u"Long-legged Myotis",
"163":u"Pallid Bat",
"164":u"Pallid Bat",
"165":u"American Pika",
"166":u"American Pika",
"167":u"Pygmy Rabbit",
"168":u"Pygmy Rabbit",
"169":u"Red Tree Vole",
"170":u"Red Tree Vole",
"171":u"Ringtail",
"172":u"Ringtail",
"173":u"Silver-haired Bat",
"174":u"Silver-haired Bat",
"175":u"Spotted Bat",
"176":u"Spotted Bat",
"177":u"Townsend's Big-eared Bat",
"178":u"Townsend's Big-eared Bat",
"179":u"Washington Ground Squirrel",
"180":u"Washington Ground Squirrel",
"181":u"Western Gray Squirrel",
"182":u"Western Gray Squirrel",
"183":u"Wolverine",
"184":u"Wolverine",
"185":u"California Mountain Kingsnake",
"186":u"California Mountain Kingsnake",
"187":u"Western Pond Turtle",
"188":u"Western Pond Turtle",
"189":u"Northern Sagebrush Lizard",
"190":u"Northern Sagebrush Lizard",
"191":u"Western Painted Turtle",
"192":u"Western Painted Turtle",
"193":u"Western Rattlesnake",
"194":u"Western Rattlesnake",
"195":u"Bell's Sparrow",
"196":u"Bell's Sparrow",
"197":u"Trumpeter Swan",
"198":u"Trumpeter Swan",
"199":u"Gray Whale",
"200":u"Gray Whale",
"201":u"Gray Wolf",
"202":u"Gray Wolf",
"203":u"Harbor Porpoise",
"204":u"Harbor Porpoise",
"205":u"Killer Whale",
"206":u"Killer Whale",
"207":u"Northern Elephant Seal",
"208":u"Northern Elephant Seal",
"209":u"Pacific Harbor Seal",
"210":u"Pacific Harbor Seal",
"211":u"Rocky Mountain Bighorn Sheep",
"212":u"Rocky Mountain Bighorn Sheep",
"213":u"Sierra Nevada Red Fox",
"214":u"Sierra Nevada Red Fox",
"215":u"Steller Sea Lion",
"216":u"Steller Sea Lion",
"217":u"White-tailed Jackrabbit",
"218":u"White-tailed Jackrabbit",
"219":u"Archimedes Springsnail",
"220":u"Beller's Ground Beetle",
"221":u"Black Petaltail",
"222":u"Blue Mud Shrimp",
"223":u"Borax Lake Ramshorn",
"224":u"Bulb Juga",
"225":u"California Floater Freshwater Mussel",
"226":u"California Mussel",
"227":u"Columbia Clubtail",
"228":u"Columbia Gorge Caddisfly",
"229":u"Columbia Gorge Hesperian",
"230":u"Crater Lake Tightcoil",
"231":u"Dall's Ramshorn",
"232":u"Dalles Mountainsnail",
"233":u"Dungeness Crab",
"234":u"Fender's Blue Butterfly",
"235":u"Flat Abalone",
"236":u"Franklin's Bumble Bee",
"237":u"Great Basin Ramshorn",
"238":u"Great Spangled Fritillary",
"239":u"Highcap Lanx",
"240":u"Hoary Elfin Butterfly",
"241":u"Insular Blue Butterfly",
"242":u"Klamath Ramshorn",
"243":u"Leona's Little Blue Butterfly",
"244":u"Lined Ramshorn",
"245":u"Malheur Cave Amphipod",
"246":u"Malheur Cave Flatworm ",
"247":u"Malheur Cave Springtail",
"248":u"Malheur Isopod",
"249":u"Malheur Pseudoscorpian",
"250":u"Mardon Skipper Butterfly",
"251":u"Monarch Butterfly",
"252":u"Native Littleneck Clam",
"253":u"Ochre Sea Star",
"254":u"Olympia Oyster",
"255":u"Oregon Shoulderband",
"256":u"Oregon Silverspot Butterfly",
"257":u"Pacific Giant Octopus",
"258":u"Pacific Walker",
"259":u"Purple-lipped Juga",
"260":u"Purple Sea Urchin",
"261":u"Razor Clam",
"262":u"Red Abalone",
"263":u"Red Sea Urchin",
"264":u"Robust Walker",
"265":u"Rock Scallop",
"266":u"Rotund Lanx",
"267":u"Scale Lanx",
"268":u"Scalloped Juga",
"269":u"Shortface Lanx",
"270":u"Sinitsin Ramshorn",
"271":u"Siskiyou Hesperian",
"272":u"Sister's Hesperian",
"273":u"Stonefly",
"274":u"Sunflower Star",
"275":u"Taylor's Checkerspot Butterfly",
"276":u"Turban Pebblesnail",
"277":u"Vernal Pool Fairy Shrimp",
"278":u"Western Bumble Bee",
"279":u"Western Ridged Mussel",
"280":u"Winged Floater Freshwater Mussel",
"281":u"Applegate's Milkvetch",
"282":u"Arrow-leaf Thelypody",
"283":u"Big-flowered Wooly Meadowfoam",
"284":u"Boggs Lake Hedge Hyssop",
"285":u"Bradshaw's Desert Parsley",
"286":u"Bull Kelp",
"287":u"Cascade Head Catchfly",
"288":u"Coast Range Fawn Lily",
"289":u"Cook's Desert Parsley",
"290":u"Crinite Mariposa Lily",
"291":u"Cronquist's Stickseed",
"292":u"Crosby's Buckwheat",
"293":u"Cusick's Lupine",
"294":u"Davis' Peppergrass",
"295":u"Dwarf Meadowfoam",
"296":u"Gentner's Fritillary",
"297":u"Golden Buckwheat",
"298":u"Golden Paintbrush",
"299":u"Greenman's Desert Parsley",
"300":u"Grimy Ivesia",
"301":u"Howell's Mariposa Lily",
"302":u"Howell's Microseris",
"303":u"Howell's Spectacular Thelypody",
"304":u"Howellia",
"305":u"Kincaid's Lupine",
"306":u"Large-flowered Rush Lily",
"307":u"Lawrence's Milkvetch",
"308":u"Macfarlane's Four o'Clock",
"309":u"Malheur Valley Fiddleneck",
"310":u"Malheur Wire-lettuce",
"311":u"McDonald's Rockcress",
"312":u"Mulford's Milkvetch",
"313":u"Native Eelgrass",
"314":u"Nelson's Checkermallow",
"315":u"Northern Wormwood",
"316":u"Oregon Semaphore Grass",
"317":u"Owyhee Clover",
"318":u"Packard's Mentzelia",
"319":u"Peacock Larkspur",
"320":u"Peck's Milkvetch",
"321":u"Pink Sandverbena",
"322":u"Point Reyes Bird's-beak",
"323":u"Pumice Grape-fern",
"324":u"Red-fruited Lomatium",
"325":u"Rough Popcornflower",
"326":u"Sea Palm",
"327":u"Sexton Mountain Mariposa Lily",
"328":u"Shiny-fruited Allocarya",
"329":u"Silvery Phacelia",
"330":u"Smooth Mentzelia",
"331":u"Snake River Goldenweed",
"332":u"South Fork John Day Milkvetch",
"333":u"Spalding's Campion",
"334":u"Sterile Milkvetch",
"335":u"Surf Grass",
"336":u"Tygh Valley Milkvetch",
"337":u"Umpqua Mariposa Lily",
"338":u"Wayside Aster",
"339":u"Western Lily",
"340":u"White-topped Aster",
"341":u"White Rock Larkspur",
"342":u"Willamette Daisy",
"343":u"Wolf's Evening Primrose",
"344":u"Alvord Lake Chub",
"345":u"Borax Lake Chub",
"346":u"Bull Trout",
"347":u"Chinook Salmon - Fall Run",
"348":u"Chinook Salmon - Spring Run",
"349":u"Chum Salmon",
"350":u"Coastal Cutthroat Trout",
"351":u"Coho Salmon",
"352":u"Western Speckled Dace group",
"353":u"Goose Lake Sucker",
"354":u"Oregon Lakes Tui Chub group",
"355":u"Lahontan Cutthroat Trout",
"356":u"Lost River Sucker",
"357":u"Miller Lake Lamprey",
"358":u"Modoc Sucker",
"359":u"Oregon Chub",
"360":u"Pit Sculpin",
"361":u"Shortnose Sucker",
"362":u"Summer Steelhead / Coastal Rainbow Trout / Columbia Basin Redband Trout",
"363":u"Oregon Basin Redband Trout",
"364":u"Winter Steelhead / Coastal Rainbow Trout",
"365":u"Warner Sucker",
"366":u"Westslope Cutthroat Trout",
"406":u"Aspen Woodlands",
"407":u"Coastal Dunes",
"408":u"Estuaries",
"409":u"Flowing Water and Riparian Habitats",
"410":u"Grasslands",
"411":u"Late Successional Mixed Conifer Forests",
"412":u"Natural Lakes",
"413":u"Oak Woodlands",
"414":u"Ponderosa Pine Woodlands",
"415":u"Sagebrush Habitats",
"416":u"Wetlands",
"367":u"Big Skate",
"368":u"Black Rockfish",
"369":u"Blue Rockfish",
"370":u"Brown Rockfish",
"371":u"Cabezon",
"372":u"Canary Rockfish",
"373":u"China Rockfish",
"374":u"Copper Rockfish",
"375":u"Deacon Rockfish",
"376":u"Eulachon",
"377":u"Grass Rockfish",
"378":u"Green Sturgeon",
"379":u"Kelp Greenling",
"380":u"Lingcod",
"381":u"Longfin Smelt",
"382":u"Millicoma Dace",
"383":u"Northern Anchovy",
"384":u"Pacific Herring",
"385":u"Pacific Lamprey",
"386":u"Pacific Sand Lance",
"387":u"Pile Perch",
"388":u"Quillback Rockfish",
"389":u"Redtail Surfperch",
"390":u"Rock Greenling",
"391":u"Shiner Perch",
"392":u"Spiny Dogfish",
"393":u"Starry Flounder",
"394":u"Striped Perch",
"395":u"Surf Smelt",
"396":u"Tiger Rockfish",
"397":u"Topsmelt",
"398":u"Umpqua Chub",
"399":u"Vermilion Rockfish",
"400":u"Western Brook Lamprey",
"401":u"Western River Lamprey",
"402":u"White Sturgeon",
"403":u"Wolf-eel",
"404":u"Yelloweye Rockfish",
"405":u"Yellowtail Rockfish",

}